allow us to not delete files
elementar/docker-s3-volume pull request #14
Opened 2020-02-14 01:05 UTC by jmahowald

It was surprising for some devs on our team to have the remote files deleted when they cleaned up locally and I figured it wouldn't hurt to give the option to turn it off.

2020-09-04 19:15 UTC, fabiob requested changes
I like the approach of exposing the sync flags so the user can change them. If you can change the variable name to `S3_SYNC_FLAGS`, I'll merge it.

2020-09-04 19:15 UTC, fabiob commented on watch
> +  while ! $AWS s3 sync "$LOCAL" "$REMOTE" $DELETE_FLAG; do
I think `S3_SYNC_FLAGS` is a better name.

2020-12-02 18:30 UTC, mirsal commented on watch
> +  while ! $AWS s3 sync "$LOCAL" "$REMOTE" $DELETE_FLAG; do
```suggestion
  while ! $AWS s3 sync "$LOCAL" "$REMOTE" $S3_SYNC_FLAGS; do
```

2020-12-02 18:30 UTC, mirsal commented on watch
> +  if ! $AWS s3 sync "$LOCAL" "$REMOTE" $DELETE_FLAG; then
```suggestion
  if ! $AWS s3 sync "$LOCAL" "$REMOTE" $S3_SYNC_FLAGS; then
```

2020-12-02 18:30 UTC, mirsal commented on README.md
> +By default if there are files that are deleted in your local file system, those will be deleted remotely.   If you wish to turn this off set the environment variable DELETE_FLAGS=":
```suggestion
By default if there are files that are deleted in your local file system, those will be deleted remotely.   If you wish to turn this off set the environment variable S3_SYNC_FLAGS=":
```

2020-12-02 18:30 UTC, mirsal commented on Dockerfile
> +ENV DELETE_FLAG "--delete"
```suggestion
ENV S3_SYNC_FLAGS "--delete"
```

2020-12-02 19:41 UTC, fabiob approved these changes

2020-12-02 19:41 UTC, merged